### ISSUE TITLE
UPDATE Sensortype Preis

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#106] opened 2016-08-11 14:47 UTC
Sensortype Preis should use unit Cent (nor €) without punctiuation (25 Cent).

**Comment by roschaefer** [comment] 2016-08-11 15:18
that's actually not a bug

**Comment by drjakob** [comment] 2016-08-11 15:19
A feature?

**Comment by roschaefer** [comment] 2016-08-11 15:28
`Change` maybe. I would just like to use `BUG` for behaviour that obviously violates the specified behaviour or produces errors. Must be fixed in a timely manner.

**Comment by roschaefer** [comment] 2017-07-22 23:22
just implemented in #487

**Closed by roschaefer** 2017-07-22 23:22 UTC
Labels: User Story
