### ISSUE TITLE
Filter "Insert Markup Menu"

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#423] opened 2017-06-16 20:41 UTC
As a reporter (Björn),
I want that the "insert markup menu" (in modal "create text component") shows only events and sensors of recent report (and not all sensors and events)
in order to use it better.

**Comment by tillprochaska** [comment] 2017-07-24 19:51
Duplicate of #397

**Closed by tillprochaska** 2017-07-24 19:51 UTC
Labels: design, User Story
